### ISSUE TITLE
Download geodatabase file for country set 1 and convert to geojson

### ISSUE THREAD

**Issue by smadha** [toladata/GLADMap#3]
Country set 1 -

Central African Republic, China, Colombia ,DR Congo, Egypt, Ethiopia, Georgia, Guatemala, Haiti, Honduras, India, Indonesia, Iraq, Japan, Jordan, Kenya, Kosovo, Kyrgyzstan, Lebanon, Liberia, Libya, Mali, Mongolia, Morocco, Myanmar, Nepal

**Comment by rpurohit3** [comment]
['CAF', 'CHN', 'COL', 'COD', 'EGY', 'ETH', 'GEO', 'GTM', 'HTI', 'HND', 'IND', 'IDN', 'IRQ', 'JPN', 'JOR', 'KEN', 'XKX', 'KGZ', 'LBN', 'LBR', 'LBY', 'MLI', 'MNG', 'MAR', 'MMR', 'NPL']
