### ISSUE TITLE
Download geodatabase file for country set 2 and convert to geojson

### ISSUE THREAD

**Issue by smadha** [toladata/GLADMap#4]
Country set 2-

Niger, Nigeria, Pakistan, Somalia, South Sudan, Sri Lanka, Sudan, Syria, Tajikistan, Timor-Leste, Tunisia, Turkey, Uganda, Ukraine, United States, West Bank and Gaza, Yemen, Zimbabwe

**Comment by kkvamsi** [comment]
"NER,NGA,PAK,SOM,SSD,LKA,SDN,SYR,TJK,TLS,TUN,TUR,UGA,UKR,USA,XWB,XGZ,YEM,ZWE"
